imports:
    - 'package-container.yml'
    - '../../route/config/package-container.yml'
    - '../../cache/config/package-container.yml'
    - '../../config/config/package-container.yml'
    - '../../bundle/config/package-container.yml'
    - '../../field/config/package-container.yml'
    - '../../container/config/package-container.yml'
    - '../../layout/config/package-container.yml'
    - '../../db/config/package-container.yml'
    - '../../http/config/package-container.yml'
    - '../../pubsub/config/package-container.yml'
    - '../../collection/config/package-container.yml'

services:
    test:
        class:     'Opine\Form\TestService'
        arguments: ['@post']