imports:
    - package-container.yml
    - ../../vendor/opine/route/config/containers/package-container.yml
    - ../../vendor/opine/cache/config/containers/package-container.yml
    - ../../vendor/opine/config/config/containers/package-container.yml
    - ../../vendor/opine/bundle/config/containers/package-container.yml
    - ../../vendor/opine/field/config/containers/package-container.yml
    - ../../vendor/opine/container/config/containers/package-container.yml
    - ../../vendor/opine/layout/config/containers/package-container.yml
    - ../../vendor/opine/db/config/containers/package-container.yml
    - ../../vendor/opine/http/config/containers/package-container.yml
    - ../../vendor/opine/pubsub/config/containers/package-container.yml
    - ../../vendor/opine/collection/config/containers/package-container.yml

services:
    test:
        class:     Opine\Form\TestService
        arguments:
            - @post
